[package]
name = "whisper"
version = "0.1.0"
authors = ["Fabian Fabro Fihra"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

vst = "0.0.1"

[lib]
name = "whisper"
crate-type = ["cdylib"]